### ISSUE TITLE
Can't get library to work (MissingSecurityHeader)

### ISSUE THREAD

**Issue by scotttag** [fog/fog-atmos#1]
I haven't been able to get this to work...

When trying to connect to Atmos, I simply get:
<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>MissingSecurityHeader</Code><Message>Your request was missing a required header.</Message></Error>

I have provided atmos_storage_endpoint, atmos_storage_token and atmos_storage_secret as required. Using fog with the Atmos S3 endpoint with the same credentials works fine so not too sure what I'm missing here...

**Comment by plribeiro3000** [comment]
Hey. Dis you manage to solve your problem?

Em sex, 6 de fev de 2015 21:19, scotttag notifications@github.com
escreveu:

**Comment by scotttag** [comment]
Yes, me being stupid and over-riding port 443 to be port 8443 (Atmos using 8443 for S3). So it was the S3 endpoint returning the error :-) Sorry!

**Comment by plribeiro3000** [comment]
No problem. Everybody does this from time to time. :smile:

Em sex, 6 de fev de 2015 21:39, scotttag notifications@github.com
escreveu:
