### ISSUE TITLE
Empty storage file.

### ISSUE THREAD

**Issue by voxik** [fog/fog-atmos#3]
During packaging fog-atmost for Fedora, rpmlint complains about zero-length-file:

```
rubygem-fog-atmos.noarch: E: zero-length
/usr/share/gems/gems/fog-atmos-0.1.0/lib/fog/atmos/storage.rb
```

Could you please clarify if this was this left intentionally empty for backward compatibility or is it just mistake?

**Comment by tokengeek** [comment]
That looks like a mistake and can be removed but @plribeiro3000 may remember something else about it.

At the very least it should have a "# This file intentionally left blank" comment if it is intentionally blank which I guess will stop that warning.

**Comment by voxik** [comment]
@tokengeek thx for explanation.

I'd like to point out that there are several other similar files, for example in fog-profitbricks. So may be it would be good idea to check all fog adapters at once, so I don't have to fill similar bugs for other projects

**Comment by tokengeek** [comment]
Yeah. We might make a `fog` issue to cover everything either removing the files or commenting the reason they exist.

I think it's possible a dynamically made require can end up `provider/service` OR `service/provider` so this may be there for that.

I'm hazily remembering something like that. I think everything should be moving to `provider/service` with the better `Fog::Provider::Service` namespace but can't recall the issue off hand.

**Comment by plribeiro3000** [comment]
So, the issue is in `fog-core`. Take a look [here](https://github.com/fog/fog-core/blob/master/lib/fog/storage.rb#L19)

We might add the comment @tokengeek suggested in the meanwhile. Would that be enough?

**Comment by voxik** [comment]
@plribeiro3000 Well, I don't think it is worth of the effort. I just wanted to check if that is false positive or not and it is indeed. Thanks for clarification.

**Comment by plribeiro3000** [comment]
@voxik So you are going to fix it on your side? Should we prioritize it on the TODO list (I have a personal one hehe)?

**Comment by voxik** [comment]
@plribeiro3000 since it is false positive, nothing needs fixing. Of course it would be nice to silence the rpmlint error, but if there is comment in the file or not, it chances nothing in reality. So if it is on last place of your TODO list, that is fine :)
